# Generated by Django 4.0.4 on 2022-05-01 09:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=35)),
                ('mobilenumber', models.CharField(max_length=15)),
                ('pincode', models.CharField(max_length=10)),
                ('house_no', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=30)),
                ('landmark', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('Not mentioned', 'Choose a state'), ('Andhra Pradesh', 'ANDHRA PRADESH'), ('Arunachal Pradesh', 'ARUNACHAL PRADESH'), ('Assam', 'ASSAM'), ('Bihar', 'BIHAR'), ('Chandigarh', 'CHANDIGARH'), ('Chhattisgarh', 'CHHATTISGARH'), ('Delhi', 'DELHI'), ('Goa', 'GOA'), ('Gujarat', 'GUJARAT'), ('Haryana', 'HARYANA'), ('Himachal Pradesh', 'HIMACHAL PRADESH'), ('Jammu & Kashmir', 'JAMMU & KASHMIR'), ('Jharkhand', 'JHARKHAND'), ('Karnataka', 'KARNATAKA'), ('Kerala', 'KERALA'), ('Madhya Pradesh', 'MADHYA PRADESH'), ('Maharastra', 'MAHARASTRA'), ('Manipur', 'MANIPUR'), ('Meghalaya', 'MEGHALAYA'), ('Mizoram', 'MIZORAM'), ('Nagaland', 'NAGALAND'), ('Odisha', 'ODISHA'), ('Punjab', 'PUNJAB'), ('Rajasthan', 'RAJASTHAN'), ('Sikkim', 'SIKKIM'), ('Tamil nadu', 'TAMIL NADU'), ('Telangana', 'TELANGANA'), ('Tripura', 'TRIPURA'), ('Uttar pradesh', 'UTTAR PRADESH'), ('Uttarakhand', 'UTTARAKHAND'), ('West bengal', 'WEST BENGAL')], max_length=20)),
                ('country', models.CharField(max_length=10)),
                ('addresstype', models.CharField(choices=[('Home', 'Home'), ('Office/Commercial', 'Office/Commercial')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ASusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('userpicture', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=40)),
                ('soldby', models.CharField(default='Not Available', max_length=20)),
                ('actualPrice', models.IntegerField()),
                ('discountedPrice', models.IntegerField()),
                ('producttype', models.CharField(max_length=15)),
                ('material', models.CharField(max_length=15)),
                ('quantity', models.IntegerField()),
                ('warranty', models.IntegerField()),
                ('countryoforigin', models.CharField(max_length=15)),
                ('onestar', models.IntegerField(default=0)),
                ('twostar', models.IntegerField(default=0)),
                ('threestar', models.IntegerField(default=0)),
                ('fourstar', models.IntegerField(default=0)),
                ('fivestar', models.IntegerField(default=0)),
                ('image1', models.ImageField(upload_to='productImages/')),
                ('image2', models.ImageField(upload_to='productImages/')),
                ('image3', models.ImageField(null=True, upload_to='productImages/')),
                ('image4', models.ImageField(null=True, upload_to='productImages/')),
                ('featuredProduct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=30)),
                ('passkey', models.CharField(max_length=20)),
                ('verificationStatus', models.BooleanField(default=False)),
                ('shoppicture', models.ImageField(default='../static/black.png', upload_to='shopimages/')),
                ('coverpic', models.ImageField(blank=True, default='../static/default.jpg', upload_to='')),
                ('description', models.CharField(default='', max_length=1000)),
                ('location', models.CharField(default='', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('date_created', models.CharField(default=datetime.date(2022, 5, 1), max_length=15)),
                ('portfolio', models.CharField(blank=True, default='', max_length=500)),
                ('fblink', models.CharField(blank=True, default='', max_length=500)),
                ('twitterlink', models.CharField(blank=True, default='', max_length=500)),
                ('instalink', models.CharField(blank=True, default='', max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usershop', to='shop.asusers')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcategoryname', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.asusers')),
                ('productname', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='productcategories', to='shop.product')),
                ('shopname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopproductcategories', to='shop.shop')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='uploadedshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shop'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_orderid', models.CharField(default='undefined', max_length=50)),
                ('transactionid', models.CharField(default='undefined', max_length=50)),
                ('signature', models.CharField(default='undefined', max_length=75)),
                ('payment_status', models.BooleanField(default=False)),
                ('delivary_status', models.BooleanField(default=False)),
                ('date', models.CharField(max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('orderby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userorders', to='shop.asusers')),
                ('ordered_products', sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='orderedproducts', to='shop.product')),
                ('shippingAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useraddress', to='shop.address')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartowner', to='shop.asusers')),
                ('products', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='productsincart', to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='address_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useraddress', to='shop.asusers'),
        ),
    ]
