# Generated by Django 4.0.4 on 2022-05-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='maplink',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
