# Generated by Django 4.0.4 on 2022-05-02 12:44

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orders_orderstatus_orders_ordertotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivary_status',
            field=models.BooleanField(default=False, help_text='Mark this once order has been delivered.'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_products',
            field=sortedm2m.fields.SortedManyToManyField(help_text="Note: Reference field only, You won't get extra money for selecting products other than customer selected ones!", related_name='orderedproducts', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderstatus',
            field=models.CharField(default='', help_text='Help customer to track orderby entering tracking status.', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shippingAddress',
            field=models.ForeignKey(help_text='Shipping address for reference.', on_delete=django.db.models.deletion.CASCADE, related_name='useraddress', to='shop.address'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=500)),
                ('date', models.CharField(max_length=20)),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercomments', to='shop.asusers')),
                ('commented_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcomments', to='shop.product')),
            ],
        ),
    ]
