# Generated by Django 4.0.4 on 2022-05-15 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_orders_orderstatus_alter_shop_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shop',
            name='date_created',
            field=models.CharField(default=datetime.date(2022, 5, 15), max_length=15),
        ),
    ]
