# Generated by Django 4.0.4 on 2022-05-17 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_average_rating_alter_shop_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Not Available', max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='date_created',
            field=models.CharField(default=datetime.date(2022, 5, 17), max_length=15),
        ),
    ]
