# Generated by Django 4.0.4 on 2022-05-18 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_description_alter_shop_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='date_created',
            field=models.CharField(default=datetime.date(2022, 5, 18), max_length=15),
        ),
    ]
