# Generated by Django 4.0.4 on 2022-05-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_shop_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='extecteddate',
            field=models.CharField(default='', max_length=20),
        ),
    ]
