# Generated by Django 4.0.4 on 2022-05-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orders_extecteddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='extecteddate',
            new_name='expecteddate',
        ),
    ]
